FROM java:8

LABEL maintainer="pycon@kakao.com"

ENV MYSQL_URL $MYSQL_URL
ENV MYSQL_USERNAME $MYSQL_USERNAME
ENV MYSQL_PASSWORD $MYSQL_PASSWORD
ENV JWT_SECRET_KEY $JWT_SECRET_KEY
ENV JWT_EXP_ACCESS $JWT_EXP_ACCESS
ENV JWT_EXP_REFRESH $JWT_EXP_REFRESH
ENV JWT_HEADER $JWT_HEADER
ENV JWT_PREFIX $JWT_PREFIX

VOLUME /tmp

EXPOSE 8080

ARG JAR_FILE=build/libs/fitness-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} fitness.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/fitness.jar"]
